# Generated by Django 6.0.2 on 2026-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_stage_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
