# Generated by Django 6.0.2 on 2026-03-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_stage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
