# Generated by Django 6.0.2 on 2026-03-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(default='ffffff', max_length=8),
        ),
    ]
