# Generated by Django 6.0.2 on 2026-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_stage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(default='ffffff', max_length=9),
        ),
    ]
