# Generated by Django 6.0.2 on 2026-03-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_task_desc_alter_task_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(verbose_name='Дата дедлайна'),
        ),
    ]
